Repository Treat-Streets/treat-streets-fe, pull requests merged in 2022-08, with the labels that each got.

#5 Circleci project setup
  .circleci/config.yml
  cypress.config.js
  cypress/e2e/app-spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: documentation

#17 Feature/build form
  package-lock.json
  package.json
  public/index.html
  src/Components/App.js
  src/Components/Header.css
  src/Components/Header.js
  src/Components/LandingPage.js
  src/Components/Nav.css
  src/Components/Nav.js
  src/Components/RegisterForm.css
  src/Components/RegisterForm.js
  src/index.css
  src/index.js
Labels: FE, Feature

#18 Update zipcode to be type String
  src/Components/RegisterForm.js
Labels: bug
