Repository Treat-Streets/treat-streets-fe, pull requests merged in 2022-09, with the labels that each got.

#34 Styling/form and thankyou
  src/Components/RegisterForm.css
  src/Components/RegisterForm.js
  src/Components/ThankYouPage.css
  src/Components/ThankYouPage.js
Labels: CSS

#38 Feature/pop up
  src/Components/App.js
  src/Components/Header.css
  src/Components/Header.js
  src/Components/MapPage.js
  src/Components/PopupPage.js
  src/Components/RegisterForm.css
  src/Components/RegisterForm.js
  src/assets/ghost.png
Labels: bug, CSS

#49 Testing/initial user flow
  .circleci/config.yml
  cypress/e2e/app-spec.cy.js
  cypress/e2e/treat-streets-spec.cy.js
  cypress/utils/graphql-test-utils.js
  src/Components/LandingPage.js
Labels: FE, testing

#54 Testing/continued user flows
  cypress/e2e/map-and-pop-up.cy.js
  cypress/e2e/register-and-thank-you.cy.js
  cypress/e2e/treat-streets.cy.js
  cypress/fixtures/locations.json
  src/Components/RegisterForm.js
Labels: FE, testing

#55 Debug/console errors
  cypress/e2e/register-and-thank-you.cy.js
  src/Components/RegisterForm.js
Labels: bug, FE

#48 Feature/zip code finder and ty map btn
  src/Components/MapPage.css
  src/Components/MapPage.js
  src/Components/RegisterForm.css
  src/Components/RegisterForm.js
  src/Components/ThankYouPage.css
  src/Components/ThankYouPage.js
Labels: enhancement, FE, CSS

#59 add glow and flicker to title
  src/Components/LandingPage.css
  src/Components/LandingPage.js
  src/Components/Nav.css
Labels: CSS

#64 center the house when clicked to open popup
  src/Components/MapPage.js
Labels: enhancement

#69 add line for browserlist production
  README.md
  package.json
  public/index.html
  src/Components/MapPage.css
  src/Components/Nav.css
  src/index.js
Labels: bug

#73 Refactor/clean up
  src/Components/App.js
  src/Components/LandingPage.css
  src/Components/LandingPage.js
  src/Components/MapPage.css
  src/Components/MapPage.js
  src/Components/NotFound.css
  src/Components/NotFound.js
  src/Components/PopupPage.css
  src/Components/PopupPage.js
  src/Components/RegisterForm.css
  src/Components/RegisterForm.js
  src/Components/ThankYouPage.css
  src/Components/ThankYouPage.js
  src/index.css
Labels: refactor
